---
## General Banner Configurations
- name: Modify the System Login Banner - /etc/issue
  copy:
    src: banner.txt
    dest: /etc/issue
    group: root
    owner: root
    mode: 644
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - AC
    - AC-8
    - AC-8(a)
    - AC-8(b)
    - AC-8(c)

- name: Modify the System Login Banner - /etc/issue.net
  copy:
    src: banner.txt
    dest: /etc/issue.net
    group: root
    owner: root
    mode: 644
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - AC
    - AC-8
    - AC-8(a)
    - AC-8(b)
    - AC-8(c)

- name: Modify the System Login Banner - /etc/motd
  copy:
    src: banner.txt
    dest: /etc/motd
    group: root
    owner: root
    mode: 644
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - AC
    - AC-8
    - AC-8(a)
    - AC-8(b)
    - AC-8(c)
  when: ansible_distribution in ["RedHat", "CentOS", "Amazon"]

- name: Modify the System Login Banner - /etc/motd
  copy:
    content: ""
    dest: /etc/motd
    group: root
    owner: root
    mode: 644
  when: ansible_distribution in ["Ubuntu"]

